## Site Meta ##
# The title of the website.
title: "Album • ZionIyes"
# The description of the website
description: "ZionIyes photography album"
# Keywords/tags for you site.
keywords: "photography, blog, photography-blog, photo-blog, dub, reggae, music, soundsystem, sound, system"
# Your copyright message.
copyright: "Copyright &copy; 2022 - ZionIyes"

## Site Configurations ##
# 1st heading of the site.
header: "ZionIyes"
# 2nd heading/sub heading of the website.
subheader: "Reggae & Dub scene photography"
# A description/bio of the website.
bio: "Capturing the best of the Belgian Reggae & Dub scene."
social:
  # Your Twitter username.
  twitter_username: "@BittieBot125"
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: "ZionIyes"
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
